service: test-serverless-framework

frameworkVersion: "3"
#teste
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: sa-east-1
  memorySize: 128
  environment:
    SQS_QUEUE_START_PROCESS: !Ref newSupplierCardMovedQueue
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "sqs:SendMessage"
          Resource: !GetAtt newSupplierCardMovedQueue.Arn

layers:
  customLibs:
    path: customLibs
    name: SAM-Events-Advance-Helpers
    description: Custom Libs shared between lambdas
    compatibleRuntimes:
      - nodejs16.x

functions:
  newSupplierCardMovedFunction:
    handler: src/newSupplierCardMovedFunction.newSupplierCardMovedFunction
    timeout: 3
    events:
      - http:
          method: post
          path: '/'
    layers:
      - !Ref CustomLibsLambdaLayer
  triggerCardMovedFunction:
    handler: src/triggerCardMovedFunction.triggerCardMovedFunction
    events:
      - sqs:
          arn: !GetAtt newSupplierCardMovedQueue.Arn
          batchSize: 10
    layers:
      - !Ref CustomLibsLambdaLayer

resources:
  Resources:
    newSupplierCardMovedQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        DelaySeconds: 0
        KmsDataKeyReusePeriodSeconds: 300 # 5 minutes (default)
        KmsMasterKeyId: alias/aws/sqs
        MaximumMessageSize: 262144 # 256 KiB (default)
        MessageRetentionPeriod: 1209600 # 14 days
        ReceiveMessageWaitTimeSeconds: 20 # long-polling
        VisibilityTimeout: 120 # 2 minutes