service: test-aws-github-actions

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: sa-east-1

functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
  newSupplierCardMovedFunction:
    handler: src/newSupplierCardMovedFunction.newSupplierCardMovedFunction
  triggerNewSupplierCardMovedFunction:
    handler: src/triggerNewSupplierCardMovedFunction.triggerNewSupplierCardMovedFunction