service: test-aws-github-actions
app: poc-cadastro-fornecedores
org: poc-evo

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: sa-east-1

functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber